// This file is auto-generated by scripts/generate-migrations-index.ts
// Do not edit manually - run 'pnpm db:generate-index' to regenerate
import type { Migration } from "kysely";
import * as migration_1746737970961_create_auth_tables from "./1746737970961_create-auth-tables.js";
import * as migration_1761485673247_add_organizations from "./1761485673247_add-organizations.js";
import * as migration_1761485673248_add_tasks_table from "./1761485673248_add-tasks-table.js";

export const migrations: Record<string, Migration> = {
	"1746737970961_create-auth-tables": migration_1746737970961_create_auth_tables,
	"1761485673247_add-organizations": migration_1761485673247_add_organizations,
	"1761485673248_add-tasks-table": migration_1761485673248_add_tasks_table,
};
