[phases.setup]
nixPkgs = ['nodejs_22']

[phases.install]
cmds = [
  'npm install -g corepack',
  'corepack enable',
  'corepack prepare pnpm@10.9.0 --activate',
  'pnpm install --frozen-lockfile'
]

[phases.build]
cmds = ['pnpm build --filter=@tasks/web']

[start]
cmd = 'cd apps/web && pnpm start'
