/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedDemoTanstackQueryImport } from './routes/_authenticated/demo.tanstack-query'
import { Route as AuthenticatedDemoStartServerFuncsImport } from './routes/_authenticated/demo.start.server-funcs'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDemoTanstackQueryRoute =
  AuthenticatedDemoTanstackQueryImport.update({
    id: '/_authenticated/demo/tanstack-query',
    path: '/demo/tanstack-query',
    getParentRoute: () => rootRoute,
  } as any)

const AuthenticatedDemoStartServerFuncsRoute =
  AuthenticatedDemoStartServerFuncsImport.update({
    id: '/_authenticated/demo/start/server-funcs',
    path: '/demo/start/server-funcs',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/demo/tanstack-query': {
      id: '/_authenticated/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof AuthenticatedDemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/demo/start/server-funcs': {
      id: '/_authenticated/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof AuthenticatedDemoStartServerFuncsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof AuthenticatedDemoTanstackQueryRoute
  '/demo/start/server-funcs': typeof AuthenticatedDemoStartServerFuncsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof AuthenticatedDemoTanstackQueryRoute
  '/demo/start/server-funcs': typeof AuthenticatedDemoStartServerFuncsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated/demo/tanstack-query': typeof AuthenticatedDemoTanstackQueryRoute
  '/_authenticated/demo/start/server-funcs': typeof AuthenticatedDemoStartServerFuncsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/tanstack-query' | '/demo/start/server-funcs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/tanstack-query' | '/demo/start/server-funcs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated/demo/tanstack-query'
    | '/_authenticated/demo/start/server-funcs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedDemoTanstackQueryRoute: typeof AuthenticatedDemoTanstackQueryRoute
  AuthenticatedDemoStartServerFuncsRoute: typeof AuthenticatedDemoStartServerFuncsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedDemoTanstackQueryRoute: AuthenticatedDemoTanstackQueryRoute,
  AuthenticatedDemoStartServerFuncsRoute:
    AuthenticatedDemoStartServerFuncsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated/demo/tanstack-query",
        "/_authenticated/demo/start/server-funcs"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated/demo/tanstack-query": {
      "filePath": "_authenticated/demo.tanstack-query.tsx"
    },
    "/_authenticated/demo/start/server-funcs": {
      "filePath": "_authenticated/demo.start.server-funcs.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
