/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SameAsNextImport } from './routes/same-as-next'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const SameAsNextRoute = SameAsNextImport.update({
  id: '/same-as-next',
  path: '/same-as-next',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/same-as-next': {
      id: '/same-as-next'
      path: '/same-as-next'
      fullPath: '/same-as-next'
      preLoaderRoute: typeof SameAsNextImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/same-as-next': typeof SameAsNextRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/same-as-next': typeof SameAsNextRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/same-as-next': typeof SameAsNextRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/same-as-next'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/same-as-next'
  id: '__root__' | '/' | '/same-as-next'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SameAsNextRoute: typeof SameAsNextRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SameAsNextRoute: SameAsNextRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/same-as-next"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/same-as-next": {
      "filePath": "same-as-next.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
