// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * T​a​s​k​s
		 */
		title: string
	}
	common: {
		/**
		 * L​o​a​d​i​n​g​.​.​.
		 */
		loading: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * S​a​v​i​n​g​.​.​.
		 */
		saving: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
		/**
		 * o​r
		 */
		or: string
	}
	auth: {
		/**
		 * S​i​g​n​ ​I​n
		 */
		signInTitle: string
		/**
		 * S​i​g​n​ ​i​n​ ​t​o​ ​a​c​c​e​s​s​ ​y​o​u​r​ ​a​c​c​o​u​n​t
		 */
		signInSubtitle: string
		/**
		 * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		signInWithGoogle: string
		/**
		 * S​i​g​n​ ​I​n
		 */
		signIn: string
		/**
		 * S​i​g​n​ ​O​u​t
		 */
		signOut: string
	}
	header: {
		/**
		 * T​o​g​g​l​e​ ​m​e​n​u
		 */
		toggleMenu: string
		/**
		 * S​w​i​t​c​h​ ​o​r​g​a​n​i​z​a​t​i​o​n
		 */
		organizationSwitcher: string
	}
	locale: {
		/**
		 * C​h​a​n​g​e​ ​l​a​n​g​u​a​g​e
		 */
		changeLanguage: string
		/**
		 * E​n​g​l​i​s​h
		 */
		en: string
		/**
		 * F​r​a​n​ç​a​i​s
		 */
		fr: string
	}
	nav: {
		/**
		 * T​o​d​o​s
		 */
		todos: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
		/**
		 * A​c​c​o​u​n​t
		 */
		account: string
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​s
		 */
		organizations: string
	}
	todos: {
		/**
		 * T​o​d​o​s
		 */
		title: string
		/**
		 * E​n​t​e​r​ ​t​a​s​k​ ​d​e​s​c​r​i​p​t​i​o​n​.​.​.
		 */
		inputPlaceholder: string
		/**
		 * A​d​d​ ​T​a​s​k
		 */
		add: string
		/**
		 * A​d​d​i​n​g​.​.​.
		 */
		adding: string
		/**
		 * T​a​s​k​s​ ​(​{​c​o​u​n​t​}​)
		 * @param {unknown} count
		 */
		listHeading: RequiredParams<'count'>
		/**
		 * N​o​ ​t​a​s​k​s​ ​y​e​t​.​ ​A​d​d​ ​o​n​e​ ​a​b​o​v​e​!
		 */
		empty: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
	}
	settings: {
		/**
		 * S​e​t​t​i​n​g​s
		 */
		title: string
		/**
		 * A​c​c​o​u​n​t
		 */
		accountTab: string
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​s
		 */
		organizationsTab: string
		account: {
			/**
			 * A​c​c​o​u​n​t​ ​I​n​f​o​r​m​a​t​i​o​n
			 */
			heading: string
			/**
			 * N​a​m​e
			 */
			nameLabel: string
			/**
			 * Y​o​u​r​ ​n​a​m​e
			 */
			namePlaceholder: string
			/**
			 * N​a​m​e​ ​u​p​d​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
			 */
			nameSuccess: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​n​a​m​e
			 */
			nameError: string
			/**
			 * E​m​a​i​l
			 */
			emailLabel: string
			/**
			 * y​o​u​r​@​e​m​a​i​l​.​c​o​m
			 */
			emailPlaceholder: string
			/**
			 * E​m​a​i​l​ ​u​p​d​a​t​e​ ​i​n​i​t​i​a​t​e​d​.​ ​C​h​e​c​k​ ​y​o​u​r​ ​i​n​b​o​x​ ​f​o​r​ ​v​e​r​i​f​i​c​a​t​i​o​n​.
			 */
			emailSuccess: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​e​m​a​i​l
			 */
			emailError: string
			/**
			 * C​h​a​n​g​i​n​g​ ​y​o​u​r​ ​e​m​a​i​l​ ​w​i​l​l​ ​r​e​q​u​i​r​e​ ​v​e​r​i​f​i​c​a​t​i​o​n
			 */
			emailVerificationNote: string
			/**
			 * E​m​a​i​l​ ​c​a​n​n​o​t​ ​b​e​ ​c​h​a​n​g​e​d​ ​f​o​r​ ​O​A​u​t​h​ ​a​c​c​o​u​n​t​s​ ​(​G​o​o​g​l​e​,​ ​e​t​c​.​)
			 */
			emailOAuthNote: string
			/**
			 * A​c​c​o​u​n​t​ ​O​v​e​r​v​i​e​w
			 */
			overviewHeading: string
			/**
			 * P​l​a​n​:
			 */
			planLabel: string
		}
		organizations: {
			/**
			 * Y​o​u​r​ ​O​r​g​a​n​i​z​a​t​i​o​n​s
			 */
			heading: string
			/**
			 * {​c​o​u​n​t​}​ ​o​r​g​a​n​i​z​a​t​i​o​n​{​c​o​u​n​t​|​s​}
			 * @param {unknown} count
			 */
			count: RequiredParams<'count' | 'count|s'>
			/**
			 * C​r​e​a​t​e​ ​O​r​g​a​n​i​z​a​t​i​o​n
			 */
			createButton: string
			/**
			 * C​r​e​a​t​e​ ​N​e​w​ ​O​r​g​a​n​i​z​a​t​i​o​n
			 */
			createHeading: string
			/**
			 * O​r​g​a​n​i​z​a​t​i​o​n​ ​n​a​m​e
			 */
			nameLabel: string
			/**
			 * A​c​m​e​ ​I​n​c
			 */
			namePlaceholder: string
			/**
			 * S​l​u​g​ ​w​i​l​l​ ​b​e​ ​a​u​t​o​-​g​e​n​e​r​a​t​e​d​ ​f​r​o​m​ ​t​h​e​ ​n​a​m​e
			 */
			slugHint: string
			/**
			 * C​a​n​c​e​l
			 */
			cancel: string
			/**
			 * C​r​e​a​t​e
			 */
			create: string
			/**
			 * C​r​e​a​t​i​n​g​.​.​.
			 */
			creating: string
			/**
			 * N​o​ ​o​r​g​a​n​i​z​a​t​i​o​n​s​ ​y​e​t​.​ ​C​r​e​a​t​e​ ​o​n​e​ ​a​b​o​v​e​!
			 */
			none: string
			/**
			 * A​c​t​i​v​e
			 */
			activeBadge: string
			/**
			 * S​l​u​g​:
			 */
			slugLabel: string
			/**
			 * R​o​l​e​:​ ​{​r​o​l​e​}
			 * @param {unknown} role
			 */
			roleLabel: RequiredParams<'role'>
			/**
			 * u​n​k​n​o​w​n
			 */
			roleUnknown: string
			/**
			 * M​e​m​b​e​r​s​ ​(​{​c​o​u​n​t​}​)
			 * @param {unknown} count
			 */
			membersHeading: RequiredParams<'count'>
			/**
			 * U​n​k​n​o​w​n​ ​u​s​e​r
			 */
			memberUnknown: string
			/**
			 * P​e​n​d​i​n​g​ ​I​n​v​i​t​a​t​i​o​n​s​ ​(​{​c​o​u​n​t​}​)
			 * @param {unknown} count
			 */
			invitationsHeading: RequiredParams<'count'>
			/**
			 * I​n​v​i​t​e​d​ ​b​y
			 */
			invitedBy: string
			/**
			 * E​x​p​i​r​e​s​ ​i​n
			 */
			expiresIn: string
			/**
			 * S​e​t​ ​A​c​t​i​v​e
			 */
			setActive: string
			/**
			 * S​w​i​t​c​h​i​n​g​.​.​.
			 */
			switching: string
			/**
			 * O​r​g​a​n​i​z​a​t​i​o​n​ ​c​r​e​a​t​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
			 */
			successCreate: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
			 */
			errorCreate: string
			/**
			 * O​r​g​a​n​i​z​a​t​i​o​n​ ​s​w​i​t​c​h​e​d​ ​s​u​c​c​e​s​s​f​u​l​l​y
			 */
			successSwitch: string
			/**
			 * F​a​i​l​e​d​ ​t​o​ ​s​w​i​t​c​h​ ​o​r​g​a​n​i​z​a​t​i​o​n
			 */
			errorSwitch: string
		}
	}
	organization: {
		/**
		 * C​r​e​a​t​e​ ​y​o​u​r​ ​o​r​g​a​n​i​z​a​t​i​o​n
		 */
		modalTitle: string
		/**
		 * C​h​o​o​s​e​ ​h​o​w​ ​y​o​u​'​l​l​ ​u​s​e​ ​t​h​i​s​ ​w​o​r​k​s​p​a​c​e
		 */
		modalDescription: string
		/**
		 * P​e​r​s​o​n​a​l​ ​w​o​r​k​s​p​a​c​e
		 */
		personalOptionTitle: string
		/**
		 * Q​u​i​c​k​ ​s​e​t​u​p​ ​f​o​r​ ​i​n​d​i​v​i​d​u​a​l​ ​u​s​e
		 */
		personalOptionDescription: string
		/**
		 * C​u​s​t​o​m​ ​o​r​g​a​n​i​z​a​t​i​o​n
		 */
		customOptionTitle: string
		/**
		 * S​e​t​ ​u​p​ ​w​i​t​h​ ​c​u​s​t​o​m​ ​n​a​m​e​ ​a​n​d​ ​s​e​t​t​i​n​g​s
		 */
		customOptionDescription: string
		/**
		 * C​r​e​a​t​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
		 */
		customFormTitle: string
		/**
		 * S​e​t​ ​u​p​ ​y​o​u​r​ ​w​o​r​k​s​p​a​c​e​ ​w​i​t​h​ ​a​ ​c​u​s​t​o​m​ ​n​a​m​e
		 */
		customFormDescription: string
		/**
		 * O​r​g​a​n​i​z​a​t​i​o​n​ ​n​a​m​e
		 */
		nameLabel: string
		/**
		 * A​c​m​e​ ​I​n​c
		 */
		namePlaceholder: string
		/**
		 * S​l​u​g​ ​w​i​l​l​ ​b​e​ ​a​u​t​o​-​g​e​n​e​r​a​t​e​d​ ​f​r​o​m​ ​t​h​e​ ​n​a​m​e
		 */
		slugHint: string
		/**
		 * B​a​c​k
		 */
		back: string
		/**
		 * C​r​e​a​t​e
		 */
		create: string
		/**
		 * C​r​e​a​t​i​n​g​.​.​.
		 */
		creating: string
		/**
		 * F​a​i​l​e​d​ ​t​o​ ​c​r​e​a​t​e​ ​o​r​g​a​n​i​z​a​t​i​o​n
		 */
		createFailed: string
	}
	errors: {
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		genericTitle: string
		/**
		 * A​n​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r​ ​o​c​c​u​r​r​e​d
		 */
		genericDescription: string
		/**
		 * G​o​ ​b​a​c​k​ ​t​o​ ​T​o​d​o​s
		 */
		goBackTodos: string
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * Tasks
		 */
		title: () => LocalizedString
	}
	common: {
		/**
		 * Loading...
		 */
		loading: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Saving...
		 */
		saving: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Confirm
		 */
		confirm: () => LocalizedString
		/**
		 * or
		 */
		or: () => LocalizedString
	}
	auth: {
		/**
		 * Sign In
		 */
		signInTitle: () => LocalizedString
		/**
		 * Sign in to access your account
		 */
		signInSubtitle: () => LocalizedString
		/**
		 * Sign in with Google
		 */
		signInWithGoogle: () => LocalizedString
		/**
		 * Sign In
		 */
		signIn: () => LocalizedString
		/**
		 * Sign Out
		 */
		signOut: () => LocalizedString
	}
	header: {
		/**
		 * Toggle menu
		 */
		toggleMenu: () => LocalizedString
		/**
		 * Switch organization
		 */
		organizationSwitcher: () => LocalizedString
	}
	locale: {
		/**
		 * Change language
		 */
		changeLanguage: () => LocalizedString
		/**
		 * English
		 */
		en: () => LocalizedString
		/**
		 * Français
		 */
		fr: () => LocalizedString
	}
	nav: {
		/**
		 * Todos
		 */
		todos: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
		/**
		 * Account
		 */
		account: () => LocalizedString
		/**
		 * Organizations
		 */
		organizations: () => LocalizedString
	}
	todos: {
		/**
		 * Todos
		 */
		title: () => LocalizedString
		/**
		 * Enter task description...
		 */
		inputPlaceholder: () => LocalizedString
		/**
		 * Add Task
		 */
		add: () => LocalizedString
		/**
		 * Adding...
		 */
		adding: () => LocalizedString
		/**
		 * Tasks ({count})
		 */
		listHeading: (arg: { count: unknown }) => LocalizedString
		/**
		 * No tasks yet. Add one above!
		 */
		empty: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
	}
	settings: {
		/**
		 * Settings
		 */
		title: () => LocalizedString
		/**
		 * Account
		 */
		accountTab: () => LocalizedString
		/**
		 * Organizations
		 */
		organizationsTab: () => LocalizedString
		account: {
			/**
			 * Account Information
			 */
			heading: () => LocalizedString
			/**
			 * Name
			 */
			nameLabel: () => LocalizedString
			/**
			 * Your name
			 */
			namePlaceholder: () => LocalizedString
			/**
			 * Name updated successfully
			 */
			nameSuccess: () => LocalizedString
			/**
			 * Failed to update name
			 */
			nameError: () => LocalizedString
			/**
			 * Email
			 */
			emailLabel: () => LocalizedString
			/**
			 * your@email.com
			 */
			emailPlaceholder: () => LocalizedString
			/**
			 * Email update initiated. Check your inbox for verification.
			 */
			emailSuccess: () => LocalizedString
			/**
			 * Failed to update email
			 */
			emailError: () => LocalizedString
			/**
			 * Changing your email will require verification
			 */
			emailVerificationNote: () => LocalizedString
			/**
			 * Email cannot be changed for OAuth accounts (Google, etc.)
			 */
			emailOAuthNote: () => LocalizedString
			/**
			 * Account Overview
			 */
			overviewHeading: () => LocalizedString
			/**
			 * Plan:
			 */
			planLabel: () => LocalizedString
		}
		organizations: {
			/**
			 * Your Organizations
			 */
			heading: () => LocalizedString
			/**
			 * {count} organization{count|s}
			 */
			count: (arg: { count: unknown }) => LocalizedString
			/**
			 * Create Organization
			 */
			createButton: () => LocalizedString
			/**
			 * Create New Organization
			 */
			createHeading: () => LocalizedString
			/**
			 * Organization name
			 */
			nameLabel: () => LocalizedString
			/**
			 * Acme Inc
			 */
			namePlaceholder: () => LocalizedString
			/**
			 * Slug will be auto-generated from the name
			 */
			slugHint: () => LocalizedString
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * Create
			 */
			create: () => LocalizedString
			/**
			 * Creating...
			 */
			creating: () => LocalizedString
			/**
			 * No organizations yet. Create one above!
			 */
			none: () => LocalizedString
			/**
			 * Active
			 */
			activeBadge: () => LocalizedString
			/**
			 * Slug:
			 */
			slugLabel: () => LocalizedString
			/**
			 * Role: {role}
			 */
			roleLabel: (arg: { role: unknown }) => LocalizedString
			/**
			 * unknown
			 */
			roleUnknown: () => LocalizedString
			/**
			 * Members ({count})
			 */
			membersHeading: (arg: { count: unknown }) => LocalizedString
			/**
			 * Unknown user
			 */
			memberUnknown: () => LocalizedString
			/**
			 * Pending Invitations ({count})
			 */
			invitationsHeading: (arg: { count: unknown }) => LocalizedString
			/**
			 * Invited by
			 */
			invitedBy: () => LocalizedString
			/**
			 * Expires in
			 */
			expiresIn: () => LocalizedString
			/**
			 * Set Active
			 */
			setActive: () => LocalizedString
			/**
			 * Switching...
			 */
			switching: () => LocalizedString
			/**
			 * Organization created successfully
			 */
			successCreate: () => LocalizedString
			/**
			 * Failed to create organization
			 */
			errorCreate: () => LocalizedString
			/**
			 * Organization switched successfully
			 */
			successSwitch: () => LocalizedString
			/**
			 * Failed to switch organization
			 */
			errorSwitch: () => LocalizedString
		}
	}
	organization: {
		/**
		 * Create your organization
		 */
		modalTitle: () => LocalizedString
		/**
		 * Choose how you'll use this workspace
		 */
		modalDescription: () => LocalizedString
		/**
		 * Personal workspace
		 */
		personalOptionTitle: () => LocalizedString
		/**
		 * Quick setup for individual use
		 */
		personalOptionDescription: () => LocalizedString
		/**
		 * Custom organization
		 */
		customOptionTitle: () => LocalizedString
		/**
		 * Set up with custom name and settings
		 */
		customOptionDescription: () => LocalizedString
		/**
		 * Create organization
		 */
		customFormTitle: () => LocalizedString
		/**
		 * Set up your workspace with a custom name
		 */
		customFormDescription: () => LocalizedString
		/**
		 * Organization name
		 */
		nameLabel: () => LocalizedString
		/**
		 * Acme Inc
		 */
		namePlaceholder: () => LocalizedString
		/**
		 * Slug will be auto-generated from the name
		 */
		slugHint: () => LocalizedString
		/**
		 * Back
		 */
		back: () => LocalizedString
		/**
		 * Create
		 */
		create: () => LocalizedString
		/**
		 * Creating...
		 */
		creating: () => LocalizedString
		/**
		 * Failed to create organization
		 */
		createFailed: () => LocalizedString
	}
	errors: {
		/**
		 * Something went wrong
		 */
		genericTitle: () => LocalizedString
		/**
		 * An unknown error occurred
		 */
		genericDescription: () => LocalizedString
		/**
		 * Go back to Todos
		 */
		goBackTodos: () => LocalizedString
	}
}

export type Formatters = {
	s: (value: unknown) => unknown
}
