// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​o​a​d​i​n​g​.​.​.
	 */
	loading: string
	/**
	 * S​a​v​e
	 */
	save: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * D​e​l​e​t​e
	 */
	'delete': string
	/**
	 * E​d​i​t
	 */
	edit: string
	/**
	 * A​d​d
	 */
	add: string
	/**
	 * C​o​n​f​i​r​m
	 */
	confirm: string
	auth: {
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * L​o​g​i​n​ ​w​i​t​h​ ​G​o​o​g​l​e
		 */
		loginWithGoogle: string
		/**
		 * L​o​g​g​e​d​ ​i​n​ ​a​s​ ​{​n​a​m​e​}
		 * @param {unknown} name
		 */
		loggedInAs: RequiredParams<'name'>
		/**
		 * P​l​e​a​s​e​ ​l​o​g​i​n​ ​t​o​ ​c​o​n​t​i​n​u​e
		 */
		loginRequired: string
	}
	tasks: {
		/**
		 * T​a​s​k​s
		 */
		title: string
		/**
		 * A​d​d​ ​T​a​s​k
		 */
		addTask: string
		/**
		 * N​e​w​ ​T​a​s​k
		 */
		newTask: string
		/**
		 * N​o​ ​t​a​s​k​s​ ​y​e​t​.​ ​C​r​e​a​t​e​ ​y​o​u​r​ ​f​i​r​s​t​ ​t​a​s​k​!
		 */
		noTasks: string
		/**
		 * E​n​t​e​r​ ​t​a​s​k​ ​d​e​s​c​r​i​p​t​i​o​n​.​.​.
		 */
		taskPlaceholder: string
		/**
		 * M​a​r​k​ ​a​s​ ​c​o​m​p​l​e​t​e
		 */
		markComplete: string
		/**
		 * M​a​r​k​ ​a​s​ ​i​n​c​o​m​p​l​e​t​e
		 */
		markIncomplete: string
		/**
		 * D​e​l​e​t​e​ ​t​a​s​k
		 */
		deleteTask: string
		/**
		 * E​d​i​t​ ​t​a​s​k
		 */
		editTask: string
		/**
		 * {​c​o​u​n​t​}​ ​t​a​s​k​{​c​o​u​n​t​|​s​}
		 * @param {unknown} count
		 */
		taskCount: RequiredParams<'count' | 'count|s'>
	}
	nav: {
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * T​a​s​k​s
		 */
		tasks: string
		/**
		 * P​r​o​f​i​l​e
		 */
		profile: string
		/**
		 * S​e​t​t​i​n​g​s
		 */
		settings: string
	}
	subscription: {
		/**
		 * P​r​e​m​i​u​m
		 */
		premium: string
		/**
		 * P​r​e​m​i​u​m​ ​F​e​a​t​u​r​e
		 */
		premiumFeature: string
		/**
		 * T​h​i​s​ ​f​e​a​t​u​r​e​ ​r​e​q​u​i​r​e​s​ ​a​ ​p​r​e​m​i​u​m​ ​s​u​b​s​c​r​i​p​t​i​o​n
		 */
		subscriptionRequired: string
		/**
		 * U​p​g​r​a​d​e​ ​t​o​ ​P​r​e​m​i​u​m
		 */
		upgrade: string
	}
	demo: {
		/**
		 * D​e​m​o​ ​F​e​a​t​u​r​e​s
		 */
		title: string
		/**
		 * S​e​r​v​e​r​ ​F​u​n​c​t​i​o​n​s​ ​D​e​m​o
		 */
		serverFunctions: string
		/**
		 * T​a​n​S​t​a​c​k​ ​Q​u​e​r​y​ ​D​e​m​o
		 */
		tanstackQuery: string
		/**
		 * F​o​r​m​s​ ​D​e​m​o
		 */
		forms: string
	}
}

export type TranslationFunctions = {
	/**
	 * Loading...
	 */
	loading: () => LocalizedString
	/**
	 * Save
	 */
	save: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Delete
	 */
	'delete': () => LocalizedString
	/**
	 * Edit
	 */
	edit: () => LocalizedString
	/**
	 * Add
	 */
	add: () => LocalizedString
	/**
	 * Confirm
	 */
	confirm: () => LocalizedString
	auth: {
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Login with Google
		 */
		loginWithGoogle: () => LocalizedString
		/**
		 * Logged in as {name}
		 */
		loggedInAs: (arg: { name: unknown }) => LocalizedString
		/**
		 * Please login to continue
		 */
		loginRequired: () => LocalizedString
	}
	tasks: {
		/**
		 * Tasks
		 */
		title: () => LocalizedString
		/**
		 * Add Task
		 */
		addTask: () => LocalizedString
		/**
		 * New Task
		 */
		newTask: () => LocalizedString
		/**
		 * No tasks yet. Create your first task!
		 */
		noTasks: () => LocalizedString
		/**
		 * Enter task description...
		 */
		taskPlaceholder: () => LocalizedString
		/**
		 * Mark as complete
		 */
		markComplete: () => LocalizedString
		/**
		 * Mark as incomplete
		 */
		markIncomplete: () => LocalizedString
		/**
		 * Delete task
		 */
		deleteTask: () => LocalizedString
		/**
		 * Edit task
		 */
		editTask: () => LocalizedString
		/**
		 * {count} task{count|s}
		 */
		taskCount: (arg: { count: unknown }) => LocalizedString
	}
	nav: {
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * Tasks
		 */
		tasks: () => LocalizedString
		/**
		 * Profile
		 */
		profile: () => LocalizedString
		/**
		 * Settings
		 */
		settings: () => LocalizedString
	}
	subscription: {
		/**
		 * Premium
		 */
		premium: () => LocalizedString
		/**
		 * Premium Feature
		 */
		premiumFeature: () => LocalizedString
		/**
		 * This feature requires a premium subscription
		 */
		subscriptionRequired: () => LocalizedString
		/**
		 * Upgrade to Premium
		 */
		upgrade: () => LocalizedString
	}
	demo: {
		/**
		 * Demo Features
		 */
		title: () => LocalizedString
		/**
		 * Server Functions Demo
		 */
		serverFunctions: () => LocalizedString
		/**
		 * TanStack Query Demo
		 */
		tanstackQuery: () => LocalizedString
		/**
		 * Forms Demo
		 */
		forms: () => LocalizedString
	}
}

export type Formatters = {
	s: (value: unknown) => unknown
}
